name: license_gatherer
description: Collect licenses of dependencies.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  pubspec_parse: ^1.0.0
  path: ^1.8.0
  args: ^2.2.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.10
