name: license_gatherer
description: Collect licenses of Dart/Flutter dependencies and generate NOTICES file.
version: 1.1.0
homepage: https://github.com/Coronon/license_gatherer

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  pubspec_parse: ^1.2.0
  path: ^1.8.1
  args: ^2.3.0
  logging: ^1.0.2
  async: ^2.8.2

dev_dependencies:
  lints: ^1.0.1
